In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [4]:
matriz = arr.reshape(2,5)
matriz

array([[ 8,  9,  2, 15, 10],
       [ 6,  4,  6,  5, 19]])

In [6]:
arr

array([ 8,  9,  2, 15, 10,  6,  4,  6,  5, 19])

In [7]:
arr.max()

19

In [9]:
matriz

array([[ 8,  9,  2, 15, 10],
       [ 6,  4,  6,  5, 19]])

In [8]:
matriz.max()

19

In [10]:
matriz.max(0)

array([ 8,  9,  6, 15, 19])

In [11]:
arr.argmax()

9

In [12]:
matriz.argmax(0)

array([0, 0, 1, 0, 1], dtype=int64)

In [13]:
arr.min()

2

In [14]:
matriz.min()

2

In [15]:
arr.argmin()

2

In [18]:
matriz.argmin(1)

array([2, 1], dtype=int64)

In [20]:
arr

array([ 8,  9,  2, 15, 10,  6,  4,  6,  5, 19])

In [19]:
arr.ptp()

17

In [21]:
matriz

array([[ 8,  9,  2, 15, 10],
       [ 6,  4,  6,  5, 19]])

In [23]:
matriz.ptp(0)

array([ 2,  5,  4, 10,  9])

In [28]:
arr.sort()
arr

array([ 2,  4,  5,  6,  6,  8,  9, 10, 15, 19])

In [27]:
np.percentile(arr, 50)

7.0

In [29]:
np.median(arr)

7.0

Mediana

In [30]:
np.median(matriz,0)

array([ 5. ,  6.5,  7.5, 10.5, 12.5])

Desviacion estandar

In [32]:
np.std(arr)

4.923413450036469

Varianza

In [33]:
np.var(arr)

24.240000000000002

Media

In [34]:
np.mean(arr)

8.4

In [38]:
a = np.array([[1,2],
              [3,4]])
b = np.array([5,6])

In [39]:
np.concatenate((a,b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [40]:
a.ndim

2

In [41]:
b.ndim

1

In [42]:
b = np.expand_dims(b, axis=0)

In [43]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [45]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])