In [1]:
import numpy as np

In [11]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
index_con = arr > 5
index_con

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
arr[index_con]
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [8]:
arr[index_con] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)