In [2]:
import numpy as np

In [4]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
piece_array = arr[:6]
piece_array

array([0, 1, 2, 3, 4, 5])

In [7]:
piece_array[:] = 0
piece_array

array([0, 0, 0, 0, 0, 0])

In [8]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [9]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [11]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])