In [4]:
import numpy as np
import numpy as pn

In [2]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.0032329185100971047

In [19]:
np.random.rand(4)

array([0.45933073, 0.04584413, 0.57343779, 0.62440667])

In [20]:
np.random.rand(4,4)

array([[0.82006175, 0.87535813, 0.00767031, 0.92163211],
       [0.23336293, 0.97293319, 0.12611027, 0.29526004],
       [0.27951826, 0.59680717, 0.5310327 , 0.62919847],
       [0.90507856, 0.88706221, 0.62086491, 0.17578479]])

In [21]:
np.random.randint(1,15)

10

In [22]:
np.random.randint(1,100,(10,10))

array([[59,  6, 45, 68, 63, 68, 39, 84, 49, 66],
       [54, 67, 51, 15, 36, 53, 89, 22, 23, 32],
       [26,  7, 97, 56, 83, 45, 24, 23, 33, 92],
       [34, 24, 48, 21, 17, 16, 42, 13, 31, 64],
       [56,  1, 84, 64, 23, 96, 23, 94, 72, 34],
       [ 9, 15,  1, 60, 90, 71, 34, 17,  9, 34],
       [17, 22, 20, 37, 22,  9, 41, 71, 62,  6],
       [ 8, 38, 38, 20, 86, 24, 64, 74, 75, 44],
       [69, 45, 78, 49, 84,  8, 86,  1, 96,  9],
       [17, 36,  7, 48, 15, 67, 81, 74, 39, 64]])