In [1]:
import numpy as np

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [8]:
tensor = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                   [[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

add or delete dimensions

In [9]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [13]:
vector = np.array([1,2,3])
print(vector)
print(vector.ndim)
vector_expand = np.expand_dims(vector, axis=0)
print(vector_expand)
vector_expand.ndim

[1 2 3]
1
[[1 2 3]]


2

In [14]:
vector = np.array([1,2,3])
print(vector)
print(vector.ndim)
vector_expand = np.expand_dims(vector, axis=0)
print(vector_expand)
print(vector_expand.ndim)
vector_squeeze = np.squeeze(vector_expand)
print(vector_squeeze)
vector_squeeze.ndim

[1 2 3]
1
[[1 2 3]]
2
[1 2 3]


1