In [1]:
import numpy as np

In [12]:
arr = np.random.randint(1,10,(3,2))
arr

array([[8, 7],
       [7, 2],
       [2, 4]])

In [13]:
arr.shape

(3, 2)

In [14]:
arr

array([[8, 7],
       [7, 2],
       [2, 4]])

In [15]:
arr.reshape(1,6)

array([[8, 7, 7, 2, 2, 4]])

In [16]:
arr.reshape(2,3)

array([[8, 7, 7],
       [2, 2, 4]])

In [17]:
np.reshape(arr,(2,3))

array([[8, 7, 7],
       [2, 2, 4]])

In [18]:
arr

array([[8, 7],
       [7, 2],
       [2, 4]])

In [19]:
np.reshape(arr,(2,3),'C')

array([[8, 7, 7],
       [2, 2, 4]])

In [20]:
np.reshape(arr,(2,3),'F')

array([[8, 2, 2],
       [7, 7, 4]])

In [21]:
np.reshape(arr,(2,3),'A')

array([[8, 7, 7],
       [2, 2, 4]])

In [22]:
np.reshape(arr,(2,4))

ValueError: cannot reshape array of size 6 into shape (2,4)