In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)
print(arr)
type(arr)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

In [6]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz_np = np.array(matriz)
print(matriz_np)
type(matriz_np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [7]:
arr[0]

1

In [8]:
arr[0] + arr[5]

7

In [9]:
matriz_np[0]

array([1, 2, 3])

In [12]:
matriz_np[0,2]

3

In [15]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [14]:
arr[0:6:2]

array([1, 3, 5])

In [23]:
arr[::3]

array([1, 4, 7])

In [21]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [22]:
arr[:-2]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
arr[-1]

9

In [25]:
arr[-3:]

array([7, 8, 9])

In [26]:
matriz_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matriz_np[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [28]:
matriz_np[1:,0:2]

array([[4, 5],
       [7, 8]])

In [31]:
m3d = [
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
    [[1,2,3],[4,5,6]],
]

m3d_np = np.array(m3d)

In [32]:
m3d_np

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])